nelmio_api_doc:
    documentation:
        securityDefinitions:
            api_key:
                type: apiKey
                description: "token"
                name: Authorization
                in: header
        security:
            - api_key: []
    areas:
        path_patterns: # an array of regexps
            - ^/(?!/doc$)

      #  host_patterns:
       #     - ^\.