security:
    encoders:
        App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
        api_key_user_provider:
              id: App\AppBundle\Security\ApiKeyUserProvider
    firewalls:
        dev:
            pattern: /(?!login|doc).*
            security: true
            stateless: true
            simple_preauth:
                authenticator: App\AppBundle\Security\ApiKeyAuthenticator
            provider: api_key_user_provider

        main:
            pattern: /(?!login|doc).*
            security: true
            stateless: true
            simple_preauth:
                authenticator: App\AppBundle\Security\ApiKeyAuthenticator
            provider: api_key_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }